name: Node.js Docker AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: isharaman8/ng-clothing:latest

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PASSWORD }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            docker container stop ng-clothing || true
            docker container rm -v -f ng-clothing || true
            docker pull isharaman8/ng-clothing:latest
            docker run -d --restart always --env-file=staging.env -p 3008:3008 --name ng-clothing isharaman8/ng-clothing:latest
